spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/socialNetwork
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: INFO
  file:
    name: ./logs/spring-social-network-logger.log
fileRepositoryFolderPosts: FileRepository
fileRepositoryFolderProfilePictures: ProfilePictures
---
environment: test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db
    username: testdb
    password: psw1234
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true